version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: intravision_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: intravision_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: intravision_backend
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=intravision_db;Username=admin;Password=admin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: intravision_frontend
    ports:
      - "3000:3000"
    environment:
    - NODE_ENV=production
    depends_on:
      - backend

volumes:
  postgres_data: