version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: intravision_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: intravision_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d intravision_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: intravision_backend
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./backend/https:/app/https:ro
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=intravision_db;Username=admin;Password=admin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: intravision_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  postgres_data: